---
- name: Provision tncv image
  hosts: nomad_instances
  become: true
  roles:
    - { role: docker, tags: ['docker'] }
    - { role: nomad, tags: ['nomad'] }
  vars:
    - docker_install_compose: false
