---
- src: https://github.com/brianshumate/ansible-nomad
  version: v1.9.3
  name: nomad

- src: https://github.com/geerlingguy/ansible-role-docker
  version: 2.5.2
  name: docker

- src: https://github.com/nierdz/ansible-consul.git
  version: origin/feat/gce-auto-join
  name: consul
