---
- name: Provision all images
  hosts: local
  become: true
  roles:
    - { role: docker, tags: ['docker'] }
    - { role: consul, tags: ['consul'] }
    - { role: vault, tags: ['vault'] }
  vars:
    - consul_raw_key: "I53CtkQUC/FpxzsoFLxalA=="
    - consul_gce_tag: "consul-server"
    - consul_node_name: "{{ ansible_hostname }}"
    - vault_consul_token: "{{ consul_raw_key }}"
    - vault_gce_project: "{{ lookup('env','GCE_PROJECT') }}"
    - vault_gce_region: "{{ lookup('env','TF_VAR_region') }}"
